### ISSUE TITLE
how to implement select2 with lock selection

### ISSUE THREAD

**Issue by sleuthhound** [kitcms/cms#8]
https://stackoverflow.com/questions/16564425/how-to-implement-select2-with-lock-selection/48111387#48111387
https://github.com/select2/select2/issues/3339
https://jsfiddle.net/o3s3y42e/4/
http://select2.github.io/select2/#locked-selections

https://github.com/select2/select2/issues/5036
https://github.com/select2/select2/issues/2658

**Comment by TariqHajeer** [comment]
did not work with ajax and defualt data togther
